# Raid Manager global configuration


[app]
APP_NAME = "RaidManager4"
APP_VERSION = "4.0.0"
BOT_ENABLED = false
API_ENABLED = false

[roblox]
roblosecurity = ""

[database]
type = "mysql"
host = "127.0.0.1"
base = "tqi"
user = "RaidManager4"
pass = "password"
# Below configuration options are for internal database pooling.
wait_for_connections = true
connection_limit = 10
queue_limit = 0


[redis]
enabled = false