# RaidManager4 Discord bot configuration

[bot]
token = ""

[commands]
enable_slash_commands = true
slash_command_guilds = []
import_requests_channel_id = ""
allow_developer_bypass = true

[files]
status_message_file = "status.json"
guidelines_file = "guidelines.json"
