# RaidManager4 Discord bot configuration

[bot]
token = ""

[commands]
enable_slash_commands = true
slash_command_guilds = []
import_requests_channel_id = "1002610487378321520"
allow_developer_bypass = true
main_group = 8592261

[files]
status_message_file = "status.json"
guidelines_file = "guidelines.json"
