# RaidManager4 Discord bot configuration

[bot]
token = ""

[commands]
enable_slash_commands = true
slash_command_guilds = []
import_requests_channel_id = ""
import_requests_approval_roles = []
allow_developer_bypass = true
main_group = 0
developers = []
ping_role_map = {raid = "", training = ""}


[files]
status_message_file = "status.json"
guidelines_file = "guidelines.json"
