# RaidManager4 Discord bot configuration

[bot]
token = ""

[commands]
enable_slash_commands = true
slash_command_guilds = []
enable_message_commands = true
message_command_prefix = ";"

[files]
status_message_file = "status.json"
guidelines_file = "guidelines.json"
