# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with: 
        host port: 3306
        mysql database: 'tqi'
        mysql user: 'RaidManager4'
        mysql password: 'password'
    - uses: actions/cache@v3.0.3
      with:
        path: raidmanager
        key: ${{ runner.os }}-raidmanager4
    - run: "npm install"
    - run: cp -r .config.example .config
    - run: "node raidmanager db:init --skip-update"
    - run: "node raidmanager start --debug --skip-update"
    - name: "Build docker image"
      run: "node raidmanager docker:build"
    - name: "Run RaidManager in docker image"
      run: "node raidmanager docker:run"
    - name: "Stop RaidManager docker image"
      run: "node raidmanager docker:stop"
      
